[package]
name = "ocrail"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.60.0", features = [
    "Foundation_Collections",
    "Globalization",
    "Graphics_Imaging",
    "Media_Ocr",
    "Storage_Streams",
] }
